# -*- coding: utf-8 -*-
"""DuckDB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jR-WsSQDUNWbznvE_KyZvDEKuO63F-w_
"""

import streamlit as st
import pandas as pd
import duckdb
from openai import OpenAI

# =========================
# CONFIGURATION GPT
# =========================

client = OpenAI(
    api_key="YOUR_API_KEY"
)

# =========================
# CHARGEMENT DONNEES
# =========================

clients = pd.read_excel("clients.xlsx")
equipements = pd.read_excel("equipements.xlsx")

# =========================
# BASE SQL EN MEMOIRE
# =========================

con = duckdb.connect()

con.register("clients_df", clients)
con.register("equipements_df", equipements)

con.execute("""
CREATE OR REPLACE TABLE clients AS
SELECT * FROM clients_df
""")

con.execute("""
CREATE OR REPLACE TABLE equipements AS
SELECT * FROM equipements_df
""")

# =========================
# PROMPT SQL
# =========================

SYSTEM_PROMPT = """
Tu es un expert SQL.

Base de données :

Table clients
- client_id
- nom
- segment

Table equipements
- client_id
- produit

Retourne uniquement une requête SQL valide DuckDB.
Pas d'explication.
Pas de markdown.
"""

# =========================
# STREAMLIT
# =========================

st.title("Chatbot Equipement Client")

question = st.text_area(
    "Posez votre question",
    height=100
)

if st.button("Exécuter"):

    if question:

        response = client.chat.completions.create(
            model="gpt-4.1",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": question}
            ]
        )

        sql_query = response.choices[0].message.content

        st.subheader("SQL généré")
        st.code(sql_query)

        try:

            result = con.execute(sql_query).df()

            st.subheader("Résultat")

            st.dataframe(result)

        except Exception as e:

            st.error(str(e))